# Generated by Django 3.2.8 on 2021-11-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20211108_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='site_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
