# Generated by Django 3.2.8 on 2021-11-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='site_url',
            field=models.TextField(null=True),
        ),
    ]
