# Generated by Django 3.2.8 on 2021-11-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20211110_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='read',
            old_name='content',
            new_name='read_url',
        ),
        migrations.RemoveField(
            model_name='read',
            name='title',
        ),
    ]
