# Generated by Django 3.2.8 on 2021-11-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20211110_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
